spring.application.name=expense-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/expense-tracker
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000